#!/bin/bash
#
# Reset a local or remote chain in preparation for rebuilding a new chain from scratch
# (corresponding to "Reset Local Environment" in the runbook).
#
# Actions performed (destructive and irreversible):
#   1. Stop L2 components (chain-stop.sh)
#   2. [local only] Stop the anvil container (docker stop anvil-chain)
#   3. Delete data/ (op-geth datadir, op-node safedb, logs, PIDs, JWT, and so on)
#   4. Delete config/<DEPLOYMENT_CONTEXT>/ (artifact/genesis/rollup/state-dump generated by this deployment)
#   5. [local only] Clear CUSTOM_GAS_TOKEN_ADDRESS in .envrc. A rebuilt anvil instance does not contain the old CGT;
#      retaining the old address would make deploy-contracts reuse a nonexistent contract. Setup redeploys it
#      and writes the new address after the value is cleared.
#
# Rebuild after reset:
#   bash scripts/chain-setup.sh <env>   # Deploy contracts and generate a pure-Fjord configuration
#   bash scripts/chain-start.sh <env>   # Start all services
#
# Usage:
#   bash scripts/chain-reset.sh [local|remote] [-y|--yes]
#     -y / --yes  Skip confirmation (an additional confirmation is required by default because the action is irreversible)
#   If env is omitted, detect it from L1_RPC_URL (localhost/127.0.0.1 is treated as local).
#
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
BASE_PATH=$(cd "$SCRIPT_DIR/../.." && pwd)
cd "$BASE_PATH"

source .envrc

# ---------- Parse arguments ----------
CHAIN_ENV=""
ASSUME_YES=0
for arg in "$@"; do
  case "$arg" in
    local|remote) CHAIN_ENV="$arg" ;;
    -y|--yes)     ASSUME_YES=1 ;;
    *) echo "Usage: bash scripts/chain-reset.sh [local|remote] [-y|--yes]" >&2; exit 1 ;;
  esac
done

if [ -z "$CHAIN_ENV" ]; then
  if echo "${L1_RPC_URL:-}" | grep -qE 'localhost|127\.0\.0\.1'; then
    CHAIN_ENV=local
  else
    CHAIN_ENV=remote
  fi
  echo "Auto-detected CHAIN_ENV=$CHAIN_ENV (from L1_RPC_URL)"
fi

# ---------- Resolve paths and validate safety (prevent accidental deletion from empty variables) ----------
if [ -z "${BASE_PATH:-}" ] || [ ! -d "$BASE_PATH/scripts" ]; then
  echo "Error: failed to resolve BASE_PATH; refusing to delete." >&2
  exit 1
fi
if [ -z "${DEPLOYMENT_CONTEXT:-}" ]; then
  echo "Error: DEPLOYMENT_CONTEXT is empty; cannot locate the config directory and refusing to delete." >&2
  exit 1
fi

DATA_DIR="$BASE_PATH/data"
CONFIG_DIR="$BASE_PATH/config/$DEPLOYMENT_CONTEXT"

# CONFIG_DIR must be strictly under $BASE_PATH/config/<nonempty>; otherwise refuse the operation.
case "$CONFIG_DIR" in
  "$BASE_PATH/config/"?*) : ;;
  *) echo "Error: CONFIG_DIR=$CONFIG_DIR is invalid; refusing to proceed." >&2; exit 1 ;;
esac

# ---------- Print the planned operations ----------
echo "============================================"
echo "  Chain Reset ($CHAIN_ENV) -- destructive and irreversible"
echo "============================================"
echo "The following actions will be performed:"
echo "  1) Stop L2 components (chain-stop.sh)"
[ "$CHAIN_ENV" = "local" ] && echo "  2) Stop the anvil container (docker stop anvil-chain)"
echo "  3) Delete the data directory:          $DATA_DIR"
echo "  4) Delete the generated configuration: $CONFIG_DIR"
[ "$CHAIN_ENV" = "local" ] && echo "  5) Clear CUSTOM_GAS_TOKEN_ADDRESS in .envrc"
if [ "$CHAIN_ENV" = "remote" ]; then
  echo ""
  echo "  Note: remote mode does not stop or clear the real L1 (anvil) or CUSTOM_GAS_TOKEN_ADDRESS;"
  echo "        it only deletes local data/ and config/$DEPLOYMENT_CONTEXT/."
fi
echo ""

# ---------- Confirmation ----------
if [ "$ASSUME_YES" != "1" ]; then
  printf "Confirm reset? Enter y to continue; any other key cancels: "
  read -r ans || ans=""
  case "$ans" in
    y|Y|yes|YES) : ;;
    *) echo "Cancelled."; exit 0 ;;
  esac
fi

# ---------- [1] Stop L2 ----------
echo ""
echo "[1] Stopping L2 components..."
bash "$BASE_PATH/scripts/chain-ops/chain-stop.sh" || true

# ---------- [2] Stop anvil (local only) ----------
if [ "$CHAIN_ENV" = "local" ]; then
  echo "[2] Stopping the anvil container..."
  docker stop anvil-chain >/dev/null 2>&1 && echo "  anvil-chain stopped" || echo "  anvil-chain is not running or is already stopped"
fi

# ---------- [3] Delete data ----------
echo "[3] Deleting data directory $DATA_DIR ..."
rm -rf "$DATA_DIR"
echo "  Deleted"

# ---------- [4] Delete generated configuration ----------
echo "[4] Deleting generated configuration $CONFIG_DIR ..."
rm -rf "$CONFIG_DIR"
echo "  Deleted"

# ---------- [5] Clear CUSTOM_GAS_TOKEN_ADDRESS (local only) ----------
if [ "$CHAIN_ENV" = "local" ]; then
  echo "[5] Clearing CUSTOM_GAS_TOKEN_ADDRESS in .envrc ..."
  python3 - <<'PY'
from pathlib import Path

path = Path(".envrc")
s = path.read_text()
lines = s.splitlines()
changed = False
for i, line in enumerate(lines):
    if line.startswith("export CUSTOM_GAS_TOKEN_ADDRESS="):
        if line != "export CUSTOM_GAS_TOKEN_ADDRESS=":
            lines[i] = "export CUSTOM_GAS_TOKEN_ADDRESS="
            changed = True
path.write_text("\n".join(lines) + "\n")
print("  Cleared" if changed else "  Already empty; no change required")
PY
fi

echo ""
echo "=== Reset complete ==="
echo "Next, rebuild the chain:"
echo "  source .envrc"
echo "  bash scripts/chain-setup.sh $CHAIN_ENV"
echo "  bash scripts/chain-start.sh $CHAIN_ENV"
